In [1]:
import pandas as pd
import numpy as np
import pyod

In [2]:
data_survey = pd.read_csv("survey.csv")
data_purchases = pd.read_csv("amazon-purchases.csv")

In [3]:
data_survey.head()

,Duration (in seconds),RecordedDate,ResponseId,Q-prolific-mturk,q-demos-age,Q-demos-hispanic,Q-demos-race,Q-demos-education,Q-demos-income,Q-demos-gender,...,Q-data-value-any_1_TEXT,Q-sell-YOUR-data,Q-sell-consumer-data,Q-small-biz-use,Q-census-use,Q-research-society,Q-attn-check,showdata,incentive,connect
0,332,9/21/2022 10:00:17,R_1ou69fj4DQGsVcp,NaN,35 - 44 years,No,Black or African American,High school diploma or GED,"$25,000 - $49,999",Female,...,NaN,No,No,No,No,No,"Yes,No,I don't know",False,bonus-50,NaN
1,488,9/21/2022 10:02:24,R_24dboHVOzohx1kw,NaN,25 - 34 years,No,White or Caucasian,Bachelor's degree,"$25,000 - $49,999",Male,...,NaN,Yes if I get part of the profit,Yes,No,Yes,Yes,"Yes,No,I don't know",False,bonus-05,NaN
2,309,9/21/2022 10:10:47,R_2UbJL30HRjK1sdD,NaN,45 - 54 years,No,White or Caucasian,High school diploma or GED,"$100,000 - $149,999",Male,...,NaN,No,No,No,No,Yes,"Yes,No,I don't know",False,bonus-05,NaN
3,339,9/21/2022 10:13:03,R_UPXamGKtmf4RVIZ,NaN,25 - 34 years,No,White or Caucasian,High school diploma or GED,"$25,000 - $49,999",Male,...,NaN,No,No,No,No,Yes,"Yes,No,I don't know",False,bonus-50,NaN
4,674,9/21/2022 11:36:51,R_2dYk5auG9Fv5Qve,NaN,35 - 44 years,Yes,White or Caucasian,"Graduate or professional degree (MA, MS, MBA, ...","$50,000 - $74,999",Male,...,NaN,No,No,No,No,No,"Yes,No,I don't know",True,control,NaN

In [4]:
data_purchases.head()

,Order Date,Purchase Price Per Unit,Quantity,Shipping Address State,Title,ASIN/ISBN (Product Code),Category,Survey ResponseID
0,2018-12-04,7.98,1.0,NJ,SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory ...,B0143RTB1E,FLASH_MEMORY,R_01vNIayewjIIKMF
1,2018-12-22,13.99,1.0,NJ,Betron BS10 Earphones Wired Headphones in Ear ...,B01MA1MJ6H,HEADPHONES,R_01vNIayewjIIKMF
2,2018-12-24,8.99,1.0,NJ,NaN,B078JZTFN3,NaN,R_01vNIayewjIIKMF
3,2018-12-25,10.45,1.0,NJ,Perfecto Stainless Steel Shaving Bowl. Durable...,B06XWF9HML,DISHWARE_BOWL,R_01vNIayewjIIKMF
4,2018-12-25,10.00,1.0,NJ,Proraso Shaving Cream for Men,B00837ZOI0,SHAVING_AGENT,R_01vNIayewjIIKMF

In [5]:
print("Data survey ",data_survey.shape)
print("Data purchases ",data_purchases.shape)

Data survey  (6325, 41)
Data purchases  (1850717, 8)

In [6]:
data_survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6325 entries, 0 to 6324
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Duration (in seconds)    6325 non-null   int64
 1   RecordedDate             6325 non-null   object
 2   ResponseId               6325 non-null   object
 3   Q-prolific-mturk         6301 non-null   object
 4   q-demos-age              6325 non-null   object
 5   Q-demos-hispanic         6325 non-null   object
 6   Q-demos-race             6325 non-null   object
 7   Q-demos-education        6325 non-null   object
 8   Q-demos-income           6325 non-null   object
 9   Q-demos-gender           6325 non-null   object
 10  Q-sexual-orientation     6325 non-null   object
 11  Q-demos-state            6325 non-null   object
 12  Q-amazon-use-howmany     6325 non-null   object
 13  Q-amazon-use-hh-size     6325 non-null   object
 14  Q-amazon-use-how-oft     6325 non-null   object
 15  Q-substance-use_1        6325 non-null   object
 16  Q-substance-use_2        6325 non-null   object
 17  Q-substance-use_3        6325 non-null   object
 18  Q-personal_1             6325 non-null   object
 19  Q-personal_2             6325 non-null   object
 20  Q-life-changes           2012 non-null   object
 21  Q-control                1275 non-null   object
 22  Q-altruism               1295 non-null   object
 23  Q-bonus-05               1265 non-null   object
 24  Q-bonus-20               1250 non-null   object
 25  Q-bonus-50               1240 non-null   object
 26  Q-data-value-05          561 non-null    object
 27  Q-data-value-20          817 non-null    object
 28  Q-data-value-50          1025 non-null   object
 29  Q-data-value-100         1129 non-null   object
 30  Q-data-value-any         975 non-null    object
 31  Q-data-value-any_1_TEXT  642 non-null    object
 32  Q-sell-YOUR-data         6325 non-null   object
 33  Q-sell-consumer-data     6325 non-null   object
 34  Q-small-biz-use          6325 non-null   object
 35  Q-census-use             6325 non-null   object
 36  Q-research-society       6325 non-null   object
 37  Q-attn-check             6325 non-null   object
 38  showdata                 6325 non-null   bool
 39  incentive                6325 non-null   object
 40  connect                  372 non-null    object
dtypes: bool(1), int64(1), object(39)
memory usage: 1.9+ MB

In [7]:
data_purchases.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1850717 entries, 0 to 1850716
Data columns (total 8 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   Order Date                1850717 non-null  object
 1   Purchase Price Per Unit   1850717 non-null  float64
 2   Quantity                  1850717 non-null  float64
 3   Shipping Address State    1762905 non-null  object
 4   Title                     1760977 non-null  object
 5   ASIN/ISBN (Product Code)  1849744 non-null  object
 6   Category                  1761259 non-null  object
 7   Survey ResponseID         1850717 non-null  object
dtypes: float64(2), object(6)
memory usage: 113.0+ MB

## data_survey

### Datos repetidos

In [8]:
data_survey = data_survey.drop_duplicates()
data_survey

,Duration (in seconds),RecordedDate,ResponseId,Q-prolific-mturk,q-demos-age,Q-demos-hispanic,Q-demos-race,Q-demos-education,Q-demos-income,Q-demos-gender,...,Q-data-value-any_1_TEXT,Q-sell-YOUR-data,Q-sell-consumer-data,Q-small-biz-use,Q-census-use,Q-research-society,Q-attn-check,showdata,incentive,connect
0,332,9/21/2022 10:00:17,R_1ou69fj4DQGsVcp,NaN,35 - 44 years,No,Black or African American,High school diploma or GED,"$25,000 - $49,999",Female,...,NaN,No,No,No,No,No,"Yes,No,I don't know",False,bonus-50,NaN
1,488,9/21/2022 10:02:24,R_24dboHVOzohx1kw,NaN,25 - 34 years,No,White or Caucasian,Bachelor's degree,"$25,000 - $49,999",Male,...,NaN,Yes if I get part of the profit,Yes,No,Yes,Yes,"Yes,No,I don't know",False,bonus-05,NaN
2,309,9/21/2022 10:10:47,R_2UbJL30HRjK1sdD,NaN,45 - 54 years,No,White or Caucasian,High school diploma or GED,"$100,000 - $149,999",Male,...,NaN,No,No,No,No,Yes,"Yes,No,I don't know",False,bonus-05,NaN
3,339,9/21/2022 10:13:03,R_UPXamGKtmf4RVIZ,NaN,25 - 34 years,No,White or Caucasian,High school diploma or GED,"$25,000 - $49,999",Male,...,NaN,No,No,No,No,Yes,"Yes,No,I don't know",False,bonus-50,NaN
4,674,9/21/2022 11:36:51,R_2dYk5auG9Fv5Qve,NaN,35 - 44 years,Yes,White or Caucasian,"Graduate or professional degree (MA, MS, MBA, ...","$50,000 - $74,999",Male,...,NaN,No,No,No,No,No,"Yes,No,I don't know",True,control,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6320,818,3/21/2023 21:59:02,R_2uKaOXO8LfgoFf3,Yes,35 - 44 years,No,Black or African American,High school diploma or GED,"Less than $25,000",Male,...,NaN,No,No,I don't know,No,No,"Yes,No,I don't know",True,bonus-50,True
6321,172,3/21/2023 22:15:05,R_3lEpFGLEmx2Sv2J,Yes,35 - 44 years,No,White or Caucasian,High school diploma or GED,"$50,000 - $74,999",Female,...,5,No,No,No,No,Yes,"Yes,No,I don't know",False,bonus-20,True
6322,579,3/21/2023 22:17:43,R_27Ee9Bw4FyMOZuZ,No,45 - 54 years,No,Other,Prefer not to say,"Less than $25,000",Female,...,NaN,No,No,No,No,No,"Yes,No,I don't know",True,control,True
6323,1244,3/21/2023 22:29:56,R_2ZZSS68rfn9BMtt,Yes,45 - 54 years,No,White or Caucasian,Bachelor's degree,"Less than $25,000",Male,...,NaN,Yes if I get part of the profit,Yes if consumers get part of the profit,Yes,Yes,Yes,"Yes,No,I don't know",False,bonus-50,True
6324,674,3/21/2023 23:03:09,R_273TMGuLM3jXisi,No,25 - 34 years,No,White or Caucasian,High school diploma or GED,"$25,000 - $49,999",Male,...,NaN,No,No,Yes,No,Yes,"Yes,No,I don't know",True,altruism,True

### Tablas de frecuencia

In [9]:
arr_ls = ["Q-prolific-mturk", "q-demos-age", "Q-demos-hispanic","Q-demos-race", 
           "Q-demos-education", "Q-demos-income", "Q-demos-gender","Q-sexual-orientation", 
           "Q-demos-state", "Q-amazon-use-howmany", "Q-amazon-use-hh-size", "Q-amazon-use-how-oft", 
           "Q-substance-use_1", "Q-substance-use_2", "Q-substance-use_3", "Q-personal_1", "Q-personal_2", 
           "Q-life-changes", "Q-control", "Q-altruism", "Q-bonus-05", "Q-bonus-20", "Q-bonus-50", "Q-data-value-05", 
           "Q-data-value-20", "Q-data-value-50", "Q-data-value-100", "Q-data-value-any", "Q-data-value-any_1_TEXT", 
           "Q-sell-YOUR-data", "Q-sell-consumer-data", "Q-small-biz-use", "Q-census-use", "Q-research-society", 
           "Q-attn-check", "showdata", "incentive", "connect"]

In [10]:
for i in arr_ls:
    print(data_survey[[i]].value_counts())
    print("--------------------------------------------------")

Q-prolific-mturk
No                  4082
Yes                 2219
Name: count, dtype: int64
--------------------------------------------------
q-demos-age
25 - 34 years    2312
35 - 44 years    1545
18 - 24 years     990
45 - 54 years     824
55 - 64 years     461
65 and older      193
Name: count, dtype: int64
--------------------------------------------------
Q-demos-hispanic
No                  5637
Yes                  688
Name: count, dtype: int64
--------------------------------------------------
Q-demos-race
White or Caucasian                                                                                        4825
Asian                                                                                                      551
Black or African American                                                                                  440
Other                                                                                                      134
White or Caucasian,Asian                                                                                    96
White or Caucasian,Black or African American                                                                72
White or Caucasian,American Indian/Native American or Alaska Native                                         66
American Indian/Native American or Alaska Native                                                            38
White or Caucasian,Other                                                                                    32
White or Caucasian,Black or African American,American Indian/Native American or Alaska Native               13
Black or African American,Asian                                                                             12
Native Hawaiian or Other Pacific Islander                                                                    7
Asian,Native Hawaiian or Other Pacific Islander                                                              6
Black or African American,American Indian/Native American or Alaska Native                                   5
White or Caucasian,Native Hawaiian or Other Pacific Islander                                                 5
White or Caucasian,American Indian/Native American or Alaska Native,Asian                                    4
White or Caucasian,Black or African American,Asian                                                           4
White or Caucasian,Asian,Native Hawaiian or Other Pacific Islander                                           3
White or Caucasian,American Indian/Native American or Alaska Native,Other                                    2
Asian,Other                                                                                                  2
Black or African American,Other                                                                              2
White or Caucasian,Black or African American,Other                                                           2
Black or African American,American Indian/Native American or Alaska Native,Asian                             1
American Indian/Native American or Alaska Native,Asian,Native Hawaiian or Other Pacific Islander,Other       1
White or Caucasian,Black or African American,Asian,Native Hawaiian or Other Pacific Islander                 1
White or Caucasian,Black or African American,Asian,Other                                                     1
Name: count, dtype: int64
--------------------------------------------------
Q-demos-education
Bachelor's degree                                                       2834
High school diploma or GED                                              2280
Graduate or professional degree (MA, MS, MBA, PhD, JD, MD, DDS, etc)    1086
Prefer not to say                                                         65
Some high school or less                                                  60
Name: count, dtype: int64
--------------------------------------------------
Q-demos-income
$25,000 - $49,999      1443
$50,000 - $74,999      1341
$100,000 - $149,999     977
$75,000 - $99,999       974
Less than $25,000       855
$150,000 or more        605
Prefer not to say       130
Name: count, dtype: int64
--------------------------------------------------
Q-demos-gender
Female               3132
Male                 3020
Other                 149
Prefer not to say      24
Name: count, dtype: int64
--------------------------------------------------
Q-sexual-orientation
heterosexual (straight)    4879
LGBTQ+                     1341
prefer not to say           105
Name: count, dtype: int64
--------------------------------------------------
Q-demos-state
California                               662
Texas                                    476
Florida                                  416
New York                                 401
Pennsylvania                             342
Illinois                                 290
Ohio                                     267
North Carolina                           217
Michigan                                 211
Georgia                                  200
Virginia                                 183
New Jersey                               167
Indiana                                  160
Washington                               154
Massachusetts                            151
Tennessee                                131
Arizona                                  129
Maryland                                 129
Minnesota                                118
Wisconsin                                116
Oregon                                   114
Kentucky                                 111
Colorado                                 109
Missouri                                  97
Alabama                                   82
South Carolina                            81
Louisiana                                 70
Oklahoma                                  70
Nevada                                    65
Connecticut                               56
Arkansas                                  55
Iowa                                      55
Kansas                                    52
Utah                                      49
Nebraska                                  42
Mississippi                               38
New Mexico                                33
West Virginia                             27
New Hampshire                             25
Rhode Island                              22
Hawaii                                    21
Idaho                                     20
Maine                                     20
District of Columbia                      16
Vermont                                   16
Delaware                                  14
South Dakota                              11
Alaska                                    11
Montana                                    9
North Dakota                               6
Wyoming                                    6
I did not reside in the United States      2
Name: count, dtype: int64
--------------------------------------------------
Q-amazon-use-howmany
1 (just me!)            4402
2                       1404
3                        325
4+                       194
Name: count, dtype: int64
--------------------------------------------------
Q-amazon-use-hh-size
2                       1984
4+                      1590
1 (just me!)            1518
3                       1233
Name: count, dtype: int64
--------------------------------------------------
Q-amazon-use-how-oft
Less than 5 times per month     4081
5 - 10 times per month          1760
More than 10 times per month     484
Name: count, dtype: int64
--------------------------------------------------
Q-substance-use_1
No                              5221
Yes                              879
I stopped in the recent past     197
Prefer not to say                 28
Name: count, dtype: int64
--------------------------------------------------
Q-substance-use_2
No                              4837
Yes                             1247
I stopped in the recent past     168
Prefer not to say                 73
Name: count, dtype: int64
--------------------------------------------------
Q-substance-use_3
No                              3382
Yes                             2707
I stopped in the recent past     188
Prefer not to say                 48
Name: count, dtype: int64
--------------------------------------------------
Q-personal_1
No                   5559
Yes                   735
Prefer not to say      31
Name: count, dtype: int64
--------------------------------------------------
Q-personal_2
No                   6190
Yes                   113
Prefer not to say      22
Name: count, dtype: int64
--------------------------------------------------
Q-life-changes
Moved place of residence                                            995
Lost a job                                                          426
Lost a job ,Moved place of residence                                217
Had a child                                                          82
Became pregnant                                                      75
Became pregnant,Had a child                                          40
Divorce,Moved place of residence                                     26
Divorce                                                              23
Moved place of residence,Became pregnant,Had a child                 19
Moved place of residence,Had a child                                 19
Moved place of residence,Became pregnant                             18
Lost a job ,Had a child                                              12
Lost a job ,Divorce,Moved place of residence                         12
Lost a job ,Divorce                                                   9
Lost a job ,Became pregnant                                           9
Lost a job ,Moved place of residence,Had a child                      8
Lost a job ,Became pregnant,Had a child                               6
Lost a job ,Moved place of residence,Became pregnant                  6
Lost a job ,Moved place of residence,Became pregnant,Had a child      6
Lost a job ,Divorce,Moved place of residence,Became pregnant          2
Divorce,Moved place of residence,Became pregnant,Had a child          1
Divorce,Moved place of residence,Became pregnant                      1
Name: count, dtype: int64
--------------------------------------------------
Q-control
Consent to share    983
Decline             292
Name: count, dtype: int64
--------------------------------------------------
Q-altruism
Consent to share    1025
Decline              270
Name: count, dtype: int64
--------------------------------------------------
Q-bonus-05
Consent to share (receive $0.05 bonus)    951
Decline                                   314
Name: count, dtype: int64
--------------------------------------------------
Q-bonus-20
Consent to share (receive $0.20 bonus)    998
Decline                                   252
Name: count, dtype: int64
--------------------------------------------------
Q-bonus-50
Consent to share  (receive $0.50 bonus)    1065
Decline                                     175
Name: count, dtype: int64
--------------------------------------------------
Q-data-value-05
No                 503
Yes                 58
Name: count, dtype: int64
--------------------------------------------------
Q-data-value-20
No                 773
Yes                 44
Name: count, dtype: int64
--------------------------------------------------
Q-data-value-50
No                 954
Yes                 71
Name: count, dtype: int64
--------------------------------------------------
Q-data-value-100
No                  975
Yes                 154
Name: count, dtype: int64
--------------------------------------------------
Q-data-value-any
More than $1.00 (enter amount)                          645
I would not consent to share my data for any amount.    330
Name: count, dtype: int64
--------------------------------------------------
Q-data-value-any_1_TEXT
10                                                                                                                  59
5.00                                                                                                                55
100                                                                                                                 49
10.00                                                                                                               48
50                                                                                                                  41
                                                                                                                    ..
2000                                                                                                                 1
20000                                                                                                                1
20000000                                                                                                             1
24.00                                                                                                                1
Maybe $2.50. I would have shared it if it allowed me to edit the file to block other information but I couldn’t.     1
Name: count, Length: 102, dtype: int64
--------------------------------------------------
Q-sell-YOUR-data
No                                 2988
Yes if I get part of the profit    2936
Yes                                 219
I don't know                        182
Name: count, dtype: int64
--------------------------------------------------
Q-sell-consumer-data
No                                         2962
Yes if consumers get part of the profit    2857
I don't know                                253
Yes                                         253
Name: count, dtype: int64
--------------------------------------------------
Q-small-biz-use
No                 2710
Yes                2046
I don't know       1569
Name: count, dtype: int64
--------------------------------------------------
Q-census-use
No              3147
I don't know    1713
Yes             1465
Name: count, dtype: int64
--------------------------------------------------
Q-research-society
Yes                   3697
No                    1456
I don't know          1172
Name: count, dtype: int64
--------------------------------------------------
Q-attn-check
Yes,No,I don't know    6325
Name: count, dtype: int64
--------------------------------------------------
showdata
False       3208
True        3117
Name: count, dtype: int64
--------------------------------------------------
incentive
altruism     1295
control      1275
bonus-05     1265
bonus-20     1250
bonus-50     1240
Name: count, dtype: int64
--------------------------------------------------
connect
True       372
Name: count, dtype: int64
--------------------------------------------------

In [11]:
data_survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6325 entries, 0 to 6324
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Duration (in seconds)    6325 non-null   int64
 1   RecordedDate             6325 non-null   object
 2   ResponseId               6325 non-null   object
 3   Q-prolific-mturk         6301 non-null   object
 4   q-demos-age              6325 non-null   object
 5   Q-demos-hispanic         6325 non-null   object
 6   Q-demos-race             6325 non-null   object
 7   Q-demos-education        6325 non-null   object
 8   Q-demos-income           6325 non-null   object
 9   Q-demos-gender           6325 non-null   object
 10  Q-sexual-orientation     6325 non-null   object
 11  Q-demos-state            6325 non-null   object
 12  Q-amazon-use-howmany     6325 non-null   object
 13  Q-amazon-use-hh-size     6325 non-null   object
 14  Q-amazon-use-how-oft     6325 non-null   object
 15  Q-substance-use_1        6325 non-null   object
 16  Q-substance-use_2        6325 non-null   object
 17  Q-substance-use_3        6325 non-null   object
 18  Q-personal_1             6325 non-null   object
 19  Q-personal_2             6325 non-null   object
 20  Q-life-changes           2012 non-null   object
 21  Q-control                1275 non-null   object
 22  Q-altruism               1295 non-null   object
 23  Q-bonus-05               1265 non-null   object
 24  Q-bonus-20               1250 non-null   object
 25  Q-bonus-50               1240 non-null   object
 26  Q-data-value-05          561 non-null    object
 27  Q-data-value-20          817 non-null    object
 28  Q-data-value-50          1025 non-null   object
 29  Q-data-value-100         1129 non-null   object
 30  Q-data-value-any         975 non-null    object
 31  Q-data-value-any_1_TEXT  642 non-null    object
 32  Q-sell-YOUR-data         6325 non-null   object
 33  Q-sell-consumer-data     6325 non-null   object
 34  Q-small-biz-use          6325 non-null   object
 35  Q-census-use             6325 non-null   object
 36  Q-research-society       6325 non-null   object
 37  Q-attn-check             6325 non-null   object
 38  showdata                 6325 non-null   bool
 39  incentive                6325 non-null   object
 40  connect                  372 non-null    object
dtypes: bool(1), int64(1), object(39)
memory usage: 1.9+ MB

## Variables a elegir dependiendo de su cantidad de datos y relevancia

La parte de arriba de las variables seleccionadas son las que salen en el codigo y la otra parte son:

- Q-amazon-use-how-oft: seleccion unica - 3 categorias
- q-demos-age: seleccion unica - 6 categorias
- Q-demos-hispanic: seleccion unica - 2 categorias
- Q-demos-education: seleccion unica - 5 categorias
- Q-demos-income: seleccion unica - 7 categorias
- Q-demos-gender: seleccion unica - 4 categorias
- Q-sexual-orientation: seleccion unica - 3 categorias 
- Q-substance-use_1: seleccion unica - 4 categorias
- Q-substance-use_2: seleccion unica - 4 categorias
- Q-substance-use_3: seleccion unica - 4 categorias
- Q-personal_1: seleccion unica - 3 categorias
- Q-personal_2: seleccion unica - 3 categorias
- Q-amazon-use-howmany: 
- Q-amazon-use-hh-size: 

- #Q-demos-state
- #Q-demos-race
----------------------------------------------------------------------------------------------------------------------------------------------

- Q-sell-YOUR-data
- Q-sell-consumer-data
- Q-small-biz-use
- Q-census-use
- Q-research-society
- Q-attn-check
- showdata
- incentive
- connect